### ISSUE TITLE
Fix stuff that relies on cookcountypropertyinfo.com

### ISSUE THREAD

**Issue by evz** [datamade/large-lots#111]
- [ ] [this](https://github.com/datamade/large-lots/blob/master/lots_client/views.py#L348) (which gives users a way to lookup their PIN by address; disabled for the moment)

**Comment by derekeder** [comment]
@fgregg found a workaround that supports direct-linking to a PIN.

This query works: www.cookcountypropertyinfo.com/cookviewerpinresults.aspx?pin=20252040200000

**Comment by evz** [comment]
Any chance we can deep link addresses, too?

**Comment by derekeder** [comment]
We can not do a deep link with addresses. Looks like just PIN for now.

The linking from the lot detail page is now working. Unfortunately, we have to drop the PIN lookup tool. 

Picking this up in #167
