### ISSUE TITLE
updates to eligible parcels data

### ISSUE THREAD

**Issue by derekeder** [datamade/large-lots#121]
We need to make a few changes to the eligible parcels data based on @fgregg's audit, namely: 

* [ ] add zoning class 
* [ ] filter out properties outside eligible zones (shapefile coming soon)

**Comment by fgregg** [comment]
I use zoning class as an eligibility requirement. Adding that field to the data will not help check that the application is for an eligible property. 

It *was* eligible at the time that I created the original file.

What we need is to check to make sure that zoning hasn't changed in the interim. To do this, we should pull info from the city's esri server for zoning.

**Comment by derekeder** [comment]
Closing this and moving the thread to another repo
