### ISSUE TITLE
Is "How do you plan to use the lot?" optional? 

### ISSUE THREAD

**Issue by fgregg** [datamade/large-lots#163]
If so, mark it as optional.

**Comment by derekeder** [comment]
That field doesn't have a red asterisk, so it is marked as optional.

The PIN field should probably have an asterisk, though.

<img width="542" alt="screen shot 2016-09-30 at 2 10 36 pm" src="https://cloud.githubusercontent.com/assets/919583/19003725/b7d657b6-8717-11e6-9ed2-ab3363c0e61b.png">

**Comment by derekeder** [comment]
Oh, looks like you said the same in #167. Closing this
