### ISSUE TITLE
Saying that a deed is invalid leads to a 500 error on the staging server

### ISSUE THREAD

**Issue by fgregg** [datamade/large-lots#173]
![screenshot from 2016-10-03 14-16-42](https://cloud.githubusercontent.com/assets/536941/19050401/068b61fe-8974-11e6-8d31-3d22854b8972.png)

On submit I get a 500 error.

**Comment by reginafcompton** [comment]
@fgregg 
I am not getting a 500 error when I replicate your form. What do you think might be going on?
