### ISSUE TITLE
custom 404 and 500 pages

### ISSUE THREAD

**Issue by derekeder** [datamade/large-lots#196]
Let's implement custom 404 not found and 500 error pages.

**Comment by reginafcompton** [comment]
Simple solution. For example, the 404:

<img width="1171" alt="screen shot 2016-11-30 at 10 12 22 am" src="https://cloud.githubusercontent.com/assets/13078679/20760395/8ead733a-b6e5-11e6-88ae-9aca786f6bd1.png">
