### ISSUE TITLE
Maps on old pilot pages won't display

### ISSUE THREAD

**Issue by stevevance** [datamade/large-lots#197]
Page: https://www.largelots.org/status/pilot_2 (East Garfield Park)
It doesn't appear on Safari and Chrome

The bug is on `largelots_status.js`: `Unexpected token ':'. Expected ')' to end an argument list.`

**Comment by reginafcompton** [comment]
Thanks Steve. This is fixed: 
https://www.largelots.org/status/pilot_1
https://www.largelots.org/status/pilot_2
