### ISSUE TITLE
press for Auburn Gresham 

### ISSUE THREAD

**Issue by derekeder** [datamade/large-lots#199]
Add press on the about page for Auburn Gresham

* https://www.dnainfo.com/chicago/20160202/auburn-gresham/chicago-large-lots-program-offers-property-auburn-gresham-for-1
* http://chicagocrusader.com/1113-2/
* http://chicago.curbed.com/2016/2/23/11099664/large-lots-program-auburn-gresham
* http://www.auburngreshamportal.org/news/10088

**Comment by reginafcompton** [comment]
This is done, plus other Pilot 6 press. https://www.largelots.org/about/
