### ISSUE TITLE
Contemplate email sending limits

### ISSUE THREAD

**Issue by evz** [datamade/large-lots#252]
It turns out that there is a 500 email per day limit on gmail. This means that, if we want to send more that that in one day we can something along these lines:

* Stagger how we send them to make sure that we are always under the limit
* Use a different service (like Mandrill) that allows for higher limits

"Staggering" could take several forms from someone just sitting there keeping track and then killing the process that sends the emails after a while to actually writing some code that does the limiting for us. The latter approach would be nice.

**Comment by hancush** [comment]
This is probably related to #280.

**Comment by reginafcompton** [comment]
We handled this issue with Mandril. Further contemplation not necessary.
