### ISSUE TITLE
Add a boolean field for organizations

### ISSUE THREAD

**Issue by reginafcompton** [datamade/large-lots#269]
When an applicant applies for a lot, they should indicate if they are an organization or individual. (We need this data to streamline the EDS process.)

**Comment by reginafcompton** [comment]
It seems like we have two options:

(1) Add an instruction in the application along the lines: "Input an organization name if an organization owns the deeded property (above). If not, then LEAVE THIS FIELD BLANK." 
(2) Add a check box next to the organization input field with something, like: "Check here, if an organization owns the deeded property above" With this solution, we need to add a boolean in the Application model: https://github.com/datamade/large-lots/blob/master/lots_admin/models.py#L35

Either can result in user error, but (2) seems more explicit. With (1), we still might get applicants who write "NA" or whatever.

**Comment by hancush** [comment]
FWIW I'm in favor of a checkbox! We could even have the organization field disabled until that box is checked.

**Comment by reginafcompton** [comment]
Yes! As you did with the good ol' PPF.
