### ISSUE TITLE
Handle shared email addresses

### ISSUE THREAD

**Issue by hancush** [datamade/large-lots#276]
Related to #270.

Some email addresses are common to multiple applicants. This round, we are manually handling these exceptions to our assumption that email is unique. Next round, let's discuss whether and how to handle applicants who – for some reason – do not have their own email, or use an email account shared with another applicant. 

n.b. DPD would like to minimize use of paper forms. Also, a unique email is required by the City's EDS system.

**Comment by reginafcompton** [comment]
Possibile solutions:
* add instructions on the application, something along the lines of "Your email address must be unique...."
* add a form validation to check first_name, last_name, email
* add an AJAX callback to autocomplete the first_name and last_name, after an applicant enters an email (i.e., move the email above the name fields)

<img width="1126" alt="screen shot 2017-11-06 at 9 32 55 am" src="https://user-images.githubusercontent.com/13078679/32448806-90a496bc-c2d5-11e7-9e91-6798d34380f3.png">

**Comment by hancush** [comment]
I'll throw in my two cents, as well:

I know we've talked in the past about shared email addresses and accessibility, but because the City's EDS system requires a unique email address and shared email addresses are an edge case, not a norm, I've come around to the idea of requiring a unique email address of Large Lots applicants. 

Short of implementing user accounts, it seems like the only solution that:

- Does not rely on user data being consistent (i.e., names being spelled and capitalized the same way). 
- Not only handles but prevents the duplication of emails, resulting in more reliable data in our system.
- Minimizes use of paper forms.

**Comment by derekeder** [comment]
@hancush I think requiring an unused email address could be a good & simple way to handle this.

Some questions, though:
* some people apply multiple times for multiple properties based on multiple deeds. how do we handle them?
* adding validation does expose to the public if someone has applied to the large lots program before. do we care about hiding that?

**Comment by hancush** [comment]
Update: We're going to allow shared email addresses.

I like Regina's idea to check for the email address in our system. If it exists, maybe we can have a modal pop up that allows the user to pick their name (if they've already applied) or enter a new one (if they're a first time applicant). That way the first / last names should be consistent.

And, since names aren't always unique, maybe we can use first name, last name, email, owned address to identify individuals?

**Comment by reginafcompton** [comment]
I think the modal could work....but then again, it's only a stone's throw from autocomplete functionality, which raises some problems with privacy (i.e., making transparent bits and pieces of our applicant database). I'd like to run it by Jeanne, first.

**Comment by hancush** [comment]
So, semi-related, we have an `Address` model that we use for the Lots and for Applications... is there any reason we couldn't have a `Person` model with a one-to-many relationship to the `Application` model? Is this _too_ big a change?

**Comment by reginafcompton** [comment]
I wonder if instead of making a suggestion for the name, we could have a generic pop-up that says something along the lines of "It looks like you already submitted an application. Please spell your first and last name exactly the same on all applications...." (i.e., if they enter an email address already in our system). If this confuses people who are sharing email addresses, we can tell them to contact Jeanne with more questions, so: "Please contact....with any questions."

**Comment by hancush** [comment]
I would like to avoid repeat user data entry, if at all possible. It's proven to be really error-prone...

**Comment by reginafcompton** [comment]
Yes - this is a tricky one. We need to assure data consistency without sacrificing user privacy. Let's send an email to Jeanne about the option to provide an applicant name, if someone enters an email currently in the database.

**Comment by hancush** [comment]
Emailed Jeanne about our approach!

**Comment by hancush** [comment]
closed via #339
