### ISSUE TITLE
Add an interface for sending emails

### ISSUE THREAD

**Issue by reginafcompton** [datamade/large-lots#280]
It might be beneficial to include an email interface for Jeanne, mainly, for simple queries, e.g., send an email to everyone on a particular step, send an email to everyone who has not been denied, etc.

I've spend significant time creating and sending bulk emails. It would be great to lighten this burden a touch. @derekeder - what do you think? or custom bulk emails something we need to budget for in the next LargeLots scope?

**Comment by hancush** [comment]
If we have time left over this cycle, we'll create this interface. [The `send_emails` management command](https://github.com/datamade/large-lots/blob/master/lots_admin/management/commands/send_emails.py) contains a lot of lessons learned; while it could use some refactoring, it's a good starting point for the internals.

**Comment by hancush** [comment]
The scope for this feature is [here](https://docs.google.com/document/d/14Hx1hycBygUEDiqWlkpe48fsR0Rvpe7FYnvZok5Ul0Y/edit?usp=sharing) (internal link).

**Comment by hancush** [comment]
the work plan for this is that i am going to refactor the management command and it extend it to send emails to custom batches of applicants (as described in the scope), and then i'll hand it over to @reginafcompton, who will take the lead on the user interface.

**Comment by reginafcompton** [comment]
(much belated) DONE.
