### ISSUE TITLE
feedback on new home page map

### ISSUE THREAD

**Issue by derekeder** [datamade/large-lots#287]
Related to #284 and #286, a few suggestions for the new home page

- [x] at the top, lets show a count in large numbers of the # lots sold and # lots available
- [x] we should make the language on the page very clear that people can not apply for lots on this map. this could be done with some more prominent text or showing only properties sold when the page initially loads 
- [x] lets figure out what fields are easy to show here. sold date would be good
- [x] can we show what was applied for?

**Comment by reginafcompton** [comment]
The staging site shows these changes: https://largelots.datamade.us/

A couple notes:
(1) The language changes depending on if pilot is active or closed, e.g., for the text above the map, it might read "The City is not accepting applications for any lots shown below" (CLOSED) or "Visit our application page to learn about buying a lot" (ACTIVE). See below for screenshot of ACTIVE.
(2) The info box for sold lots indicates the pilot and the day the pilot closed. I need to contact Jeanne to get the "sold date" for each pilot.

<img width="868" alt="screen shot 2017-10-10 at 10 58 22 am" src="https://user-images.githubusercontent.com/13078679/31396783-ff329214-ada9-11e7-8fee-3eaadb1f0619.png">
