### ISSUE TITLE
Verify address in application

### ISSUE THREAD

**Issue by reginafcompton** [datamade/large-lots#295]
An applicant applied for a lot with [the correct pin](https://www.largelots.org/apply-confirm/c5d5f779-2c00-41fd-bbc9-b00e1e3c0195/), but then input the wrong address. 

The application was for this lot: https://www.largelots.org/#/browse?pin=20184080270000

Let's figure out a way to prevent this to avoid confusion at time of closing and/or throughout the review process.

**Comment by hancush** [comment]
What if we had users input the PIN and auto-fill the address via AJAX a la your suggestion in #276?

**Comment by derekeder** [comment]
this approach assumes our address/PIN data is always correct. Can we safely make this assumption @fgregg?

**Comment by reginafcompton** [comment]
closed via PR #316
