### ISSUE TITLE
[META] Improvements to application form

### ISSUE THREAD

**Issue by hancush** [datamade/large-lots#307]
## Scoped work

> DataMade will make modifications to the lot application, which will improve the overall backend review process. Improvements will include: explicit identification of applications for organizations; validation of lot addresses; clearer retention of “planned use”; and integration of the new document search from the Recorder of Deeds. 

## Related issues

- [x] #269 
- [x] #295 
- [x] #299
- [x] #300

**Comment by reginafcompton** [comment]
DONE!
