### ISSUE TITLE
Large Lots errors not logging to Semaphor

### ISSUE THREAD

**Issue by reginafcompton** [datamade/large-lots#343]
I received a Sentry notification with a LargeLots error - someone trying to access the `apply-confirm` page with an inaccurate tracking id, hence raising a DoesNotExist error and showing a 500. 

More importantly, it looks like this error did not get logged to Semaphor. We should check that we have Semaphor logging for largelots.org set-up as we want it to be.

**Comment by hancush** [comment]
FWIW – I wired up deployment notifications, but I'm 50% sure I didn't do errors. I'll do this in the next two weeks, prior to the commencement of the next round.

**Comment by reginafcompton** [comment]
The Semabot callback URL had not been added to Sentry. It's all set-up now.
