### ISSUE TITLE
add instructions for new round startup to the wiki

### ISSUE THREAD

**Issue by hancush** [datamade/large-lots#349]
- make the new data (data-making lives in the lis repo)
- upload lots for upcoming round as new dataset to carto
- add new program area boundaries to [`chicago_community_areas`](https://datamade.carto.com/tables/chicago_community_areas/public/map) table in carto
  - add row
  - grab geometry from `boundaries.geojson`
- update CURRENT_PILOT, CURRENT_CARTODB, CURRENT_BOUNDARIES, START_DATE END_DATE in lots settings

**Comment by hancush** [comment]
waiting on this 'til #353 is complete!

**Comment by hancush** [comment]
also, n.b., made some changes in #353 so the carto stuff is set in the `local_settings` file.

**Comment by reginafcompton** [comment]
[closing per the new wiki page!](https://github.com/datamade/large-lots/wiki/How-to-prepare-for-a-new-cycle-of-Large-Lots)
