### ISSUE TITLE
refactor map logic placing sold lots in their rounds 

### ISSUE THREAD

**Issue by hancush** [datamade/large-lots#361]
we have a hard-coded block that tries to guess which pilot a lot was sold in:

https://github.com/datamade/large-lots/blob/ef6dfd89c35d9687879022649ae88a25663caf94/templates/index.html#L217-L260

i'm not sure if it holds moving forward. for example, were all lots sold in austin, sold as part of the austin pilot? (same q for all of the community areas in `pilot_lookups`.)

ideally, we would add the pilot to the list of sold lots, as we expand it, so we don't need to worry about logic. if that's not possible, we should consider ways to make this logic more future proof.

**Comment by reginafcompton** [comment]
We are going to remove this element from the info panel....since it's a pretty small detail and not worth the hours and energy to capture.
