### ISSUE TITLE
Enable HTTPS

### ISSUE THREAD

**Issue by derekeder** [datamade/large-lots#94]
We should enable and force HTTPS on largelots.org.

**Comment by evz** [comment]
:rocket:

**Comment by derekeder** [comment]
NICE!

On Fri, Aug 28, 2015 at 11:57 AM, Eric van Zanten <notifications@github.com>
wrote:

> [image: :rocket:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datamade/large-lots/issues/94#issuecomment-135831879>.
>



-- 
Derek Eder
@derekeder <https://twitter.com/#!/derekeder>
derek.eder@gmail.com
derekeder.com
