### ISSUE TITLE
cookviewer does not support HTTPS

### ISSUE THREAD

**Issue by derekeder** [datamade/large-lots#98]
Looking up images from cookviewer will not work on many browsers now that largelots.org is using https #94. 

https://cookviewer1.cookcountyil.gov/Jsviewer/image_viewer/requestImg.aspx?16123100180000=

We will probably want to look into caching the images.

**Comment by fgregg** [comment]
Might want to make a little web service that does this (if pin is requested and it has seen it before return the cached image, if not fetch the image from cookviewer, return and cache)

**Comment by derekeder** [comment]
Resolved with 914dfc3cdf8cb4ff4deeaba80be820c8a3e4e846
